### ISSUE TITLE
Não utilizar conjunção entre os milhares e as centenas quando o número acaba nas dezenas ou nas unidades e a centenas não são nulas

### ISSUE THREAD

**Issue by Anami-II** [thiagodp/extenso#1]
https://www.normaculta.com.br/numeros-por-extenso/#:~:text=Em%20textos%20escritos%2C%20devem%20ser,bem%20como%20os%20numerais%20fracion%C3%A1rios.

Exemplo:
O "e" em negrito não deve existir.
499.999,00
Está retornando: quatrocentos e noventa e nove mil **e** novecentos e noventa e nove reais
Deve retornar: quatrocentos e noventa e nove mil novecentos e noventa e nove reais

**Comment by thiagodp** [comment]
Grato @Anami-II. O uso de vírgula como separador é outra coisa que não deveria estar sendo realizado. Vou tentar liberar uma versão com ambas as correções.

**Comment by thiagodp** [comment]
Feito para a [v2.0.0](https://github.com/thiagodp/extenso/releases/tag/v2.0.0)
